GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5f58270aa36e79265cb5b71d

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name" : "Anima Krishna",
    "subscribedToChannel" : "Beypore Sultan"
}

###

DELETE http://localhost:3000/subscribers/5f582731a36e79265cb5b71e

###

PATCH  http://localhost:3000/subscribers/5f582c726f734f26cc3b7837
Content-Type: application/json

{
    "subscribedToChannel" : "Web Dev Simplified"
}